### ISSUE TITLE
Allow a cache when proxying

### ISSUE THREAD

**Issue by chrishas35** [benliles/djangopypi#25]
Rather than simply redirecting to pypi, it'd be nice to have an additional setting that will enable caching of missing packages on the local djangopypi server. What are your thoughts on including something like this? I'm willing to work on implementing if others desire it too.

**Comment by benliles** [comment]
I was actually working on this in addition to a setting to turn it into a mirror of pypi.python.org. The problem with just caching the ones that are missing is that you won't get updates for packages which is why I'm wrapping it in with the mirror support. I figured that there could be a flag for mirroring only requested packages.

**Comment by chrishas35** [comment]
Is there a branch with this code?

**Comment by benliles** [comment]
No, I was doing the work on the master branch, it's mainly a management command for now. I was going to refactor it once I got the management command working so that it would be more useable.

**Comment by kbrownlees** [comment]
This would be a great feature, I am also willing to put in some time if it would help.
