### ISSUE TITLE
413 error if sdist is too big

### ISSUE THREAD

**Issue by cournape** [benliles/djangopypi#5]
Hi,

I have a djangopypi instance installed, and it works well, but when I tried to upload a "big" (~1.7MB) tarball, I got back a 413 http error.

**Comment by benliles** [comment]
I just tested on my instance with a 50MB tarball and received no errors. It is possible that your server isn't configured to allow uploads of that size. I ran into this on one of my hosted services. In that case, Django was using a temporary file in memory for uploads and was killed by the host for too much RAM usage. You can set the FILE_UPLOAD_MAX_MEMORY_SIZE or change the FILE_UPLOAD_HANDLERS so that the memory handler is not used. I chose to change the FILE_UPLOAD_HANDLERS, but it depends on your host.

For more information, see http://docs.djangoproject.com/en/dev/topics/http/file-uploads/#changing-upload-handler-behavior
